app:
  name: "YOLOv8 Multi-thread Detection"
  width: 1200
  height: 800
  fps_update_interval: 1  # Cập nhật FPS mỗi giây

video:
  path: "rtsp://admin:Atin%40123%23@192.168.1.233/Streaming/Channels/1"
  # path: rtsp://admin:admin123@192.168.1.111:554/cam/realmonitor?channel=1&subtype=0
  target_fps: 30

model:
  path: resources/models/last_1280_yolov8s.pt
  # path: "resources/models/yolov8m.pt"  # model cũ
  device: "cuda"  # hoặc "cpu"
  input_size: 1280  # Kích thước đầu vào của model (thay vì 640 mặc định)
  confidence_threshold: 0.4
  classes: [0]  # 0 là class 'person' trong COCO dataset

display:
  bbox_color: [0, 255, 0]  # BGR
  text_color: [0, 255, 0]  # BGR
  text_thickness: 2
  box_thickness: 2

polygon:
  enabled: false  # Bật/tắt tính năng detect chỉ trong polygon
  line_color: [0, 255, 255]  # Màu đường polygon (BGR - Yellow)
  line_thickness: 2
  fill_alpha: 0.2  # Độ trong suốt vùng fill (0-1)
