app:
  name: "YOLOv8 Multi-thread Detection"
  width: 1200
  height: 800
  fps_update_interval: 1  # Cập nhật FPS mỗi giây

video:
  # path: "resources/videos/test.mp4"
  path: rtsp://admin:admin123@192.168.1.111:554/cam/realmonitor?channel=1&subtype=0
  target_fps: 30

model:
  path: resources\models\yolov8m.pt
  # path: "resources/models/yolov8m.pt"
  device: "cuda"  # hoặc "cpu"
  confidence_threshold: 0.45
  classes: [0]  # 0 là class 'person' trong COCO dataset

display:
  bbox_color: [0, 255, 0]  # BGR
  text_color: [0, 255, 0]  # BGR
  text_thickness: 2
  box_thickness: 2

polygon:
  enabled: true  # Bật/tắt tính năng detect chỉ trong polygon
  line_color: [0, 255, 255]  # Màu đường polygon (BGR - Yellow)
  line_thickness: 2
  fill_alpha: 0.2  # Độ trong suốt vùng fill (0-1)
